import { IAccessToken } from './access-token';
import { IUserOrProjectAttachment } from './attachments-details';
import { IProjectDetailsData } from './project-details';
import { ITechnologyUsedInProject } from './technology';
import { IUserAssignedCvData } from './user-cv';
import { IUserEducationDetails } from './user-education';
import { IUserPermissionsRole } from './user-permissions-role';
import { IUserWorkHistory } from './user-work-history';
import { IUserWorkType } from './user-work-type';

export interface IUserDetails {
  id: number;
  email: string;
  password: string;
  name: null | string;
  surname: null | string;
  positionDescription: null | string;
  language: null | string;
  endReason: null | string;
  avatarUrl: string;
  phone: null | string;
  city: null | string;
  salary: number;
  address: null | string;
  skills: null | string;
  experience: null | string;
  isBanned: boolean;
  banReason: null | string;
  birthday: null | string;
  cvId: null | number;
  startDate: null | string;
  endDate: null | string;
  workTypeId: null | number;
  status: string;
  upwork: null | string;
  github: null | string;
  linkedin: null | string;
  telegramTag: null | string;
  individualEntrepreneurName: null | string;
  individualEntrepreneurAddress: null | string;
  individualEntrepreneurIndividualTaxNumber: null | number;
  individualEntrepreneurBankAccounNumber: null | string;
  individualEntrepreneurBankName: null | string;
  individualEntrepreneurBankCode: null | number;
  individualEntrepreneurBeneficiaryBank: null | string;
  individualEntrepreneurSwiftCode: null | string;
  defaultCoverLetter: null | string;
  createdAt: string;
  updatedAt: string;
  cv: null | IUserAssignedCvData;
  workType: IUserWorkType | null;
  roles: IUserPermissionsRole[];
  token?: IAccessToken;
  leadingInProjects: IProjectDetailsData[];
  participatingInProjects: IProjectDetailsData[];
  attachedAttachments: IUserOrProjectAttachment[];
  publishedAttachments: IUserOrProjectAttachment[];
  techStack: ITechnologyUsedInProject[];
  educationInfo: IUserEducationDetails[];
  workHistory: IUserWorkHistory[];
}
