import { IAccessToken } from './access-token';
import { IUserOrProjectAttachment } from './attachments-details';
import { IProjectDetailsData } from './project-details';
import { ITechnologyUsedInProject } from './technology';
import { IUserAssignedCvData } from './user-cv';
import { IUserEducationDetails } from './user-education';
import { IUserPermissionsRole } from './user-permissions-role';
import { IUserWorkHistory } from './user-work-history';
import { IUserWorkType } from './user-work-type';

export interface IUserDetails {
  id: number;
  email: string;
  password: string;
  name: string;
  surname: string;
  positionDescription: string;
  language: string;
  endReason: string;
  avatarUrl: string;
  phone: string;
  city: string;
  salary: number;
  address: string;
  skills: string;
  experience: string;
  isBanned: boolean;
  banReason: string;
  birthday: string;
  cvId: number;
  startDate: string;
  endDate: string;
  workTypeId: number;
  status: string;
  upwork: string;
  github: string;
  linkedin: string;
  telegramTag: string;
  individualEntrepreneurName: string;
  individualEntrepreneurAddress: string;
  individualEntrepreneurIndividualTaxNumber: number;
  individualEntrepreneurBankAccounNumber: string;
  individualEntrepreneurBankName: string;
  individualEntrepreneurBankCode: number;
  individualEntrepreneurBeneficiaryBank: string;
  individualEntrepreneurSwiftCode: string;
  defaultCoverLetter: string;
  createdAt: string;
  updatedAt: string;
  cv: IUserAssignedCvData;
  workType: IUserWorkType;
  roles: IUserPermissionsRole[];
  token?: IAccessToken;
  leadingInProjects: IProjectDetailsData[];
  participatingInProjects: IProjectDetailsData[];
  attachedAttachments: IUserOrProjectAttachment[];
  publishedAttachments: IUserOrProjectAttachment[];
  techStack: ITechnologyUsedInProject[];
  educationInfo: IUserEducationDetails[];
  workHistory: IUserWorkHistory[];
}
